package cn.lsy99.middleware1.dao;

import cn.lsy99.middleware1.entity.IdList;
import cn.lsy99.middleware1.entity.IdListExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Mapper
@Component

public interface IdListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_list
     *
     * @mbggenerated
     */
    int countByExample(IdListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_list
     *
     * @mbggenerated
     */
    int deleteByExample(IdListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_list
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_list
     *
     * @mbggenerated
     */
    int insert(IdList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_list
     *
     * @mbggenerated
     */
    int insertSelective(IdList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_list
     *
     * @mbggenerated
     */
    List<IdList> selectByExample(IdListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_list
     *
     * @mbggenerated
     */
    IdList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_list
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") IdList record, @Param("example") IdListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_list
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") IdList record, @Param("example") IdListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IdList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IdList record);
}