package cn.lsy99.middleware1.entity;

public class IdList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column id_list.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column id_list.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column id_list.id
     *
     * @return the value of id_list.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column id_list.id
     *
     * @param id the value for id_list.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column id_list.name
     *
     * @return the value of id_list.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column id_list.name
     *
     * @param name the value for id_list.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }
}