package cn.lsy99.middleware1.entity;

import java.util.Date;

public class MessageQueue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_queue.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_queue.provider_name
     *
     * @mbggenerated
     */
    private String providerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_queue.consumer_name
     *
     * @mbggenerated
     */
    private String consumerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_queue.topic
     *
     * @mbggenerated
     */
    private String topic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_queue.message
     *
     * @mbggenerated
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_queue.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_queue.id
     *
     * @return the value of message_queue.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_queue.id
     *
     * @param id the value for message_queue.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_queue.provider_name
     *
     * @return the value of message_queue.provider_name
     *
     * @mbggenerated
     */
    public String getProviderName() {
        return providerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_queue.provider_name
     *
     * @param providerName the value for message_queue.provider_name
     *
     * @mbggenerated
     */
    public void setProviderName(String providerName) {
        this.providerName = providerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_queue.consumer_name
     *
     * @return the value of message_queue.consumer_name
     *
     * @mbggenerated
     */
    public String getConsumerName() {
        return consumerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_queue.consumer_name
     *
     * @param consumerName the value for message_queue.consumer_name
     *
     * @mbggenerated
     */
    public void setConsumerName(String consumerName) {
        this.consumerName = consumerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_queue.topic
     *
     * @return the value of message_queue.topic
     *
     * @mbggenerated
     */
    public String getTopic() {
        return topic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_queue.topic
     *
     * @param topic the value for message_queue.topic
     *
     * @mbggenerated
     */
    public void setTopic(String topic) {
        this.topic = topic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_queue.message
     *
     * @return the value of message_queue.message
     *
     * @mbggenerated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_queue.message
     *
     * @param message the value for message_queue.message
     *
     * @mbggenerated
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_queue.time
     *
     * @return the value of message_queue.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_queue.time
     *
     * @param time the value for message_queue.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }
}