package cn.lsy99.middleware1.entity;

public class Provider {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provider.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provider.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provider.topic
     *
     * @mbggenerated
     */
    private String topic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provider.id
     *
     * @return the value of provider.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provider.id
     *
     * @param id the value for provider.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provider.name
     *
     * @return the value of provider.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provider.name
     *
     * @param name the value for provider.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provider.topic
     *
     * @return the value of provider.topic
     *
     * @mbggenerated
     */
    public String getTopic() {
        return topic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provider.topic
     *
     * @param topic the value for provider.topic
     *
     * @mbggenerated
     */
    public void setTopic(String topic) {
        this.topic = topic;
    }
}